export const POSITIONS = {
  DISTANCE: 'distance',
  RANGE: 'range',
  CLINCH: 'clinch',
  GROUND_TOP: 'groundTop',
  GROUND_GUARD: 'groundGuard',
};

// Which positions you can move to manually (costs 1 action)
export const POSITION_TRANSITIONS = {
  [POSITIONS.DISTANCE]: [POSITIONS.RANGE],
  [POSITIONS.RANGE]: [POSITIONS.DISTANCE, POSITIONS.CLINCH],
  [POSITIONS.CLINCH]: [POSITIONS.RANGE, POSITIONS.GROUND_TOP, POSITIONS.GROUND_GUARD],
  [POSITIONS.GROUND_TOP]: [POSITIONS.CLINCH, POSITIONS.GROUND_GUARD],
  [POSITIONS.GROUND_GUARD]: [POSITIONS.CLINCH, POSITIONS.GROUND_TOP],
};

export const ACTIVE_CARDS = {
  jab: {
    id: 'jab',
    name: 'Jab',
    type: 'strike',
    description: 'Golpe rápido e direto',
    positions: [POSITIONS.RANGE],
    moveTo: null,         // no movement
    cooldown: 1,
    maxUses: Infinity,
    baseDamage: 15,
    damageAttrs: { boxing: 0.7, speed: 0.3 },
    tags: ['light', 'fast'],
  },
  cross: {
    id: 'cross',
    name: 'Cruz',
    type: 'strike',
    description: 'Soco reto de trás, potente',
    positions: [POSITIONS.RANGE],
    moveTo: null,
    cooldown: 2,
    maxUses: Infinity,
    baseDamage: 25,
    damageAttrs: { boxing: 0.6, power: 0.4 },
    tags: ['heavy', 'power'],
  },
  overhand: {
    id: 'overhand',
    name: 'Overhand',
    type: 'strike',
    description: 'Soco curvado que fecha distância',
    positions: [POSITIONS.DISTANCE],
    moveTo: POSITIONS.RANGE,
    cooldown: 3,
    maxUses: 3,
    baseDamage: 35,
    damageAttrs: { boxing: 0.4, power: 0.6 },
    tags: ['heavy', 'engage', 'power'],
  },
  highKick: {
    id: 'highKick',
    name: 'Chute Alto',
    type: 'strike',
    description: 'Chute na cabeça, alto risco',
    positions: [POSITIONS.DISTANCE, POSITIONS.RANGE],
    moveTo: null,
    cooldown: 3,
    maxUses: 3,
    baseDamage: 40,
    damageAttrs: { kickboxing: 0.5, power: 0.3, speed: 0.2 },
    tags: ['heavy', 'risky'],
  },
  doubleLeg: {
    id: 'doubleLeg',
    name: 'Queda Dupla',
    type: 'takedown',
    description: 'Fechada dupla, leva ao chão',
    positions: [POSITIONS.RANGE],
    moveTo: POSITIONS.GROUND_TOP,
    cooldown: 3,
    maxUses: 2,
    baseDamage: 0,
    damageAttrs: { wrestling: 0.6, strength: 0.4 },
    tags: ['engage', 'grappling'],
  },
  takedownDefense: {
    id: 'takedownDefense',
    name: 'Defesa de Queda',
    type: 'defense',
    description: 'Bloqueia tentativa de queda',
    positions: [POSITIONS.RANGE, POSITIONS.CLINCH, POSITIONS.DISTANCE],
    moveTo: null,
    cooldown: 1,
    maxUses: Infinity,
    baseDamage: 0,
    damageAttrs: { wrestling: 0.5, takedownDefense: 0.5 },
    tags: ['defense', 'grappling'],
  },
  // Specials — limited use
  rearNaked: {
    id: 'rearNaked',
    name: 'Mata-leão',
    type: 'submission',
    description: 'Finalização pelas costas',
    positions: [POSITIONS.GROUND_TOP],
    moveTo: null,
    cooldown: 4,
    maxUses: 2,
    baseDamage: 100,
    damageAttrs: { bjj: 0.6, submissionOffense: 0.4 },
    tags: ['submission', 'finish'],
  },
  clinchKnee: {
    id: 'clinchKnee',
    name: 'Joelhada no Clinch',
    type: 'strike',
    description: 'Joelhada curta no clinch',
    positions: [POSITIONS.CLINCH],
    moveTo: null,
    cooldown: 2,
    maxUses: Infinity,
    baseDamage: 20,
    damageAttrs: { muayThai: 0.6, strength: 0.4 },
    tags: ['closeRange'],
  },
  legKick: {
    id: 'legKick',
    name: 'Chute na Perna',
    type: 'strike',
    description: 'Diminui a mobilidade do oponente',
    positions: [POSITIONS.DISTANCE, POSITIONS.RANGE],
    moveTo: null,
    cooldown: 2,
    maxUses: Infinity,
    baseDamage: 12,
    damageAttrs: { kickboxing: 0.5, power: 0.3, speed: 0.2 },
    tags: ['light', 'debuff'],
  },
  singleLeg: {
    id: 'singleLeg',
    name: 'Queda de Uma Perna',
    type: 'takedown',
    description: 'Queda rápida de uma perna',
    positions: [POSITIONS.RANGE],
    moveTo: POSITIONS.GROUND_TOP,
    cooldown: 2,
    maxUses: 3,
    baseDamage: 0,
    damageAttrs: { wrestling: 0.5, speed: 0.5 },
    tags: ['engage', 'grappling'],
  },
  elbowStrike: {
    id: 'elbowStrike',
    name: 'Cotovelada',
    type: 'strike',
    description: 'Corte profundo, alto dano',
    positions: [POSITIONS.CLINCH, POSITIONS.GROUND_TOP],
    moveTo: null,
    cooldown: 3,
    maxUses: 3,
    baseDamage: 30,
    damageAttrs: { muayThai: 0.5, power: 0.5 },
    tags: ['heavy', 'cut'],
  },
  groundAndPound: {
    id: 'groundAndPound',
    name: 'Ground and Pound',
    type: 'strike',
    description: 'Socos no chão',
    positions: [POSITIONS.GROUND_TOP],
    moveTo: null,
    cooldown: 2,
    maxUses: Infinity,
    baseDamage: 22,
    damageAttrs: { boxing: 0.3, power: 0.4, wrestling: 0.3 },
    tags: ['ground'],
  },
  armbar: {
    id: 'armbar',
    name: 'Chave de Braço',
    type: 'submission',
    description: 'Finalização de braço',
    positions: [POSITIONS.GROUND_TOP, POSITIONS.GROUND_GUARD],
    moveTo: null,
    cooldown: 4,
    maxUses: 1,
    baseDamage: 100,
    damageAttrs: { bjj: 0.7, submissionOffense: 0.3 },
    tags: ['submission', 'finish'],
  },
};

export const PASSIVE_CARDS = {
  heavyHands: {
    id: 'heavyHands',
    name: 'Mão Pesada',
    description: '+15% dano em golpes de poder',
    type: 'passive',
    effect: { type: 'damageMult', tags: ['power'], value: 0.15 },
  },
  solidBase: {
    id: 'solidBase',
    name: 'Base Sólida',
    description: '+20% defesa de queda quando em Alcance',
    type: 'passive',
    effect: { type: 'takedownDefenseBonus', position: POSITIONS.RANGE, value: 0.20 },
  },
  bloodCold: {
    id: 'bloodCold',
    name: 'Sangue Frio',
    description: '-1 cooldown nas cartas especiais quando perdendo',
    type: 'passive',
    effect: { type: 'cooldownReductionLoser', value: 1 },
  },
  dirtyFight: {
    id: 'dirtyFight',
    name: 'Jogo Sujo',
    description: '+25% chance de penalidade no oponente',
    type: 'passive',
    effect: { type: 'foulChance', value: 0.25 },
  },
  student: {
    id: 'student',
    name: 'Estudioso',
    description: 'No primeiro turno, revela carta do oponente',
    type: 'passive',
    effect: { type: 'revealFirstTurn' },
  },
  marathon: {
    id: 'marathon',
    name: 'Maratona',
    description: '-10% fadiga por round',
    type: 'passive',
    effect: { type: 'fatigueReduction', value: 0.10 },
  },
};

export const DEFAULT_LOADOUTS = {
  striker: {
    active: ['jab', 'cross', 'overhand', 'highKick', 'legKick'],
    passive: ['heavyHands'],
  },
  grappler: {
    active: ['jab', 'doubleLeg', 'singleLeg', 'clinchKnee', 'takedownDefense'],
    passive: ['solidBase'],
  },
  pressure: {
    active: ['jab', 'cross', 'overhand', 'clinchKnee', 'groundAndPound'],
    passive: ['marathon'],
  },
  patient: {
    active: ['jab', 'cross', 'takedownDefense', 'legKick', 'elbowStrike'],
    passive: ['student'],
  },
  balanced: {
    active: ['jab', 'cross', 'doubleLeg', 'takedownDefense', 'legKick'],
    passive: ['solidBase'],
  },
};

export function getDefaultLoadout(gamePlanKey) {
  return DEFAULT_LOADOUTS[gamePlanKey] || DEFAULT_LOADOUTS.balanced;
}
